@HotelListing_HostAddress = http://localhost:5291

GET {{HotelListing_HostAddress}}/hotels/

###

POST {{HotelListing_HostAddress}}/hotels/
Content-Type: application/json
{
    "id": 3,
    "name": "Hotel California",
    "address": "42 Sunset Boulevard, Los Angeles, CA",
    "rating": 4.7   
}
###

@id=3
GET {{HotelListing_HostAddress}}/hotels/{{id}}

###

PUT {{HotelListing_HostAddress}}/hotels/{{id}}
Content-Type: application/json
{
    "id": 3,
    "name": "Hotel California",
    "address": "42 Sunset Boulevard, Los Angeles, CA",
    "rating": 4.7
}

###

DELETE {{HotelListing_HostAddress}}/hotels/{{id}}

###





@id=2
GET {{HotelListing_HostAddress}}/api/countries

###

POST {{HotelListing_HostAddress}}/api/countries
Content-Type: application/json

{
  "name": "Test Country",
  "shortName": "TC"
}

###

DELETE {{HotelListing_HostAddress}}/api/countries/{{id}}

###

GET {{HotelListing_HostAddress}}/api/countries/{{id}}

###

PUT {{HotelListing_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
    "countryId": 2,
    "name": "Las Vegas",
    "shortName": "LA"
}

###
